In [1]:
import pandas as pd

In [123]:
df = pd.read_json("all/raw_data1.json")
df1 = pd.read_json("all/raw_data2.json")
df2 = pd.read_json("all/raw_data3.json")
df3 = pd.read_json("all/raw_data4.json")
df4 = pd.read_json("all/raw_data5.json")
df5 = pd.read_json("all/raw_data6.json")
df6 = pd.read_json("all/raw_data7.json")
df7 = pd.read_json("all/raw_data8.json")
dfi = pd.concat([df, df1, df2, df3, df4, df5, df6, df7])

# dfi = pd.read_json("all/raw_data2.json")

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [108]:
dfi.head()

,agebracket,backupnotes,contractedfromwhichpatientsuspected,currentstatus,dateannounced,detectedcity,detecteddistrict,detectedstate,entryid,estimatedonsetdate,...,notes,numcases,patientnumber,source1,source2,source3,statecode,statepatientnumber,statuschangedate,typeoftransmission
0,20,Student from Wuhan,,Recovered,30/01/2020,Thrissur,Thrissur,Kerala,NaN,,...,Travelled from Wuhan,1,1,https://twitter.com/vijayanpinarayi/status/122...,https://weather.com/en-IN/india/news/news/2020...,,KL,KL-TS-P1,14/02/2020,Imported
1,,Student from Wuhan,,Recovered,02/02/2020,Alappuzha,Alappuzha,Kerala,NaN,,...,Travelled from Wuhan,1,2,https://www.indiatoday.in/india/story/kerala-r...,https://weather.com/en-IN/india/news/news/2020...,,KL,KL-AL-P1,14/02/2020,Imported
2,,Student from Wuhan,,Recovered,03/02/2020,Kasaragod,Kasaragod,Kerala,NaN,,...,Travelled from Wuhan,1,3,https://www.indiatoday.in/india/story/kerala-n...,https://twitter.com/ANI/status/122422148580539...,https://weather.com/en-IN/india/news/news/2020...,KL,KL-KS-P1,14/02/2020,Imported
3,45,Travel history to Italy and Austria,,Recovered,02/03/2020,East Delhi (Mayur Vihar),East Delhi,Delhi,NaN,,...,"Travelled from Austria, Italy",1,4,https://www.indiatoday.in/india/story/not-a-ja...,https://economictimes.indiatimes.com/news/poli...,,DL,DL-P1,15/03/2020,Imported
4,24,"Travel history to Dubai, Singapore contact",,Recovered,02/03/2020,Hyderabad,Hyderabad,Telangana,NaN,,...,"Travelled from Dubai to Bangalore on 20th Feb,...",1,5,https://www.deccanherald.com/national/south/qu...,https://www.indiatoday.in/india/story/coronavi...,https://www.thehindu.com/news/national/coronav...,TG,TS-P1,02/03/2020,Imported

In [124]:
# df_k = dfi[dfi['detectedstate'] == "Kerala"]
df_k = dfi
df_k['patientnumber'] = 'P' + df_k['patientnumber'].astype(str)

In [165]:
df_k1 = df_k.drop(['detectedstate', 'source1', 'source2', 'source3', 'statecode', 'statepatientnumber', 'statuschangedate', 'numcases'], axis =1 )

In [166]:
ids = ['P6','P4','P35','P29','P22','P35','P36','P37','P51','P43','P36','P37','P38','P44','P45','P64','P30','P41','P78','P73','P77','P74','P95','E0','P146','P81','P138','P160','P153','P171','P157','P142','P218','P172','P108','P117','P248','P260','P201','P132','P137','P191','P182','P272','P295','P285','P389','P200','P196','P269','P141','P225','P297','P301','P302','P150','P159','P380','P56','P369','P370','P573','P362','P596','P531','P630','P632','P634','P311','P643','P486','P525','P301','P348','P683','P385','P532','P316','P469','P717','P681','P726','P493','P502','P523','P764','P577','P654','P514','P922','P629','P513','P658','P1007','P983','P689','P653','P1076','P1128','P758','P713','P1316','P1131','P873','P753','P1406','P757','P1443','P809','P1500','P1716','P1262','P1263','P1215','P1017','P2868','P756','P1457','P1950','P3731','P1442','P3236','P1717','P2587','P4555','P4563','P2113','P3797','P3489','P4917','P4870','P1714','P3490','P5546','P2859','P5937','P2892','P4370','P1014','P4860','P3830','P4906','P4862','P2482','P1212','P6209','P4864','P6834','P1062','P4905','P6268','P2111','P1418','P5385','P3835','P6266','P5387','P4859','P7681','P3834','P4933','P6212','P4860','P6833','P8460','P6211','P10747','P10454','P8464','P8463','P9266','P11590','P4861','P8894','P8898','P1013','P11597','P11589','P4866','P3244','P10745','P2891','P4869','P9257','P6212','P12587','P3237','P3241','P13637','P11579','P12589','P12591','P11583','P14707','P13700','P8894','P2106','P12589','P12576','P7678','P8461','P13641','P13641','P20415','P14724','P16136','P20410','P4866','P14708','P18793','P21703','P19074','KA-C0','P14721','P3833','P18789','P21710','P14723','P23425','P21463','P20413','P20416','P21463','P28005','P23153','P14708','P14722','P17364','P28464','P13658','P26467','P23429','P24602','P24603','P24602','P24605','P24848','P24846','P23429','P24602','P24603','P29443','P12961','P12575','P12564','P29897','P29898','P29899','P12584','P2098','P28008','P29405','P30609','P28995','P29443,29422','P21570','P29515','P28929','P13662','P30076','P31176','P30610','P20411','P14704','P29425','P30071','P31854','P32852','P31301','P31298','P31857','P31856','P32851','P24604','P24602','P29421','P24604','P24848','P29416','P29417','P29408','P29421','P29906','P32857','P31913','P23146','P23151','P31909','P31910','P29422','P30068','P35873','P27635','P27636','P27627','P14','P1','P2','P4','P43454']
ptr = "P6,|P6 |P6$|P4,|P4 |P4$|P35,|P35 |P35$|P29,|P29 |P29$|P22,|P22 |P22$|P35,|P35 |P35$|P36,|P36 |P36$|P37,|P37 |P37$|P51,|P51 |P51$|P43,|P43 |P43$|P36,|P36 |P36$|P37,|P37 |P37$|P38,|P38 |P38$|P44,|P44 |P44$|P45,|P45 |P45$|P64,|P64 |P64$|P30,|P30 |P30$|P41,|P41 |P41$|P78,|P78 |P78$|P73,|P73 |P73$|P77,|P77 |P77$|P74,|P74 |P74$|P95,|P95 |P95$|P146,|P146 |P146$|P81,|P81 |P81$|P138,|P138 |P138$|P160,|P160 |P160$|P153,|P153 |P153$|P171,|P171 |P171$|P157,|P157 |P157$|P142,|P142 |P142$|P218,|P218 |P218$|P172,|P172 |P172$|P108,|P108 |P108$|P117,|P117 |P117$|P248,|P248 |P248$|P260,|P260 |P260$|P201,|P201 |P201$|P132,|P132 |P132$|P137,|P137 |P137$|P191,|P191 |P191$|P182,|P182 |P182$|P272,|P272 |P272$|P295,|P295 |P295$|P285,|P285 |P285$|P389,|P389 |P389$|P200,|P200 |P200$|P196,|P196 |P196$|P269,|P269 |P269$|P141,|P141 |P141$|P225,|P225 |P225$|P297,|P297 |P297$|P301,|P301 |P301$|P302,|P302 |P302$|P150,|P150 |P150$|P159,|P159 |P159$|P380,|P380 |P380$|P56,|P56 |P56$|P369,|P369 |P369$|P370,|P370 |P370$|P573,|P573 |P573$|P362,|P362 |P362$|P596,|P596 |P596$|P531,|P531 |P531$|P630,|P630 |P630$|P632,|P632 |P632$|P634,|P634 |P634$|P311,|P311 |P311$|P643,|P643 |P643$|P486,|P486 |P486$|P525,|P525 |P525$|P301,|P301 |P301$|P348,|P348 |P348$|P683,|P683 |P683$|P385,|P385 |P385$|P532,|P532 |P532$|P316,|P316 |P316$|P469,|P469 |P469$|P717,|P717 |P717$|P681,|P681 |P681$|P726,|P726 |P726$|P493,|P493 |P493$|P502,|P502 |P502$|P523,|P523 |P523$|P764,|P764 |P764$|P577,|P577 |P577$|P654,|P654 |P654$|P514,|P514 |P514$|P922,|P922 |P922$|P629,|P629 |P629$|P513,|P513 |P513$|P658,|P658 |P658$|P1007,|P1007 |P1007$|P983,|P983 |P983$|P689,|P689 |P689$|P653,|P653 |P653$|P1076,|P1076 |P1076$|P1128,|P1128 |P1128$|P758,|P758 |P758$|P713,|P713 |P713$|P1316,|P1316 |P1316$|P1131,|P1131 |P1131$|P873,|P873 |P873$|P753,|P753 |P753$|P1406,|P1406 |P1406$|P757,|P757 |P757$|P1443,|P1443 |P1443$|P809,|P809 |P809$|P1500,|P1500 |P1500$|P1716,|P1716 |P1716$|P1262,|P1262 |P1262$|P1263,|P1263 |P1263$|P1215,|P1215 |P1215$|P1017,|P1017 |P1017$|P2868,|P2868 |P2868$|P756,|P756 |P756$|P1457,|P1457 |P1457$|P1950,|P1950 |P1950$|P3731,|P3731 |P3731$|P1442,|P1442 |P1442$|P3236,|P3236 |P3236$|P1717,|P1717 |P1717$|P2587,|P2587 |P2587$|P4555,|P4555 |P4555$|P4563,|P4563 |P4563$|P2113,|P2113 |P2113$|P3797,|P3797 |P3797$|P3489,|P3489 |P3489$|P4917,|P4917 |P4917$|P4870,|P4870 |P4870$|P1714,|P1714 |P1714$|P3490,|P3490 |P3490$|P5546,|P5546 |P5546$|P2859,|P2859 |P2859$|P5937,|P5937 |P5937$|P2892,|P2892 |P2892$|P4370,|P4370 |P4370$|P1014,|P1014 |P1014$|P4860,|P4860 |P4860$|P3830,|P3830 |P3830$|P4906,|P4906 |P4906$|P4862,|P4862 |P4862$|P2482,|P2482 |P2482$|P1212,|P1212 |P1212$|P6209,|P6209 |P6209$|P4864,|P4864 |P4864$|P6834,|P6834 |P6834$|P1062,|P1062 |P1062$|P4905,|P4905 |P4905$|P6268,|P6268 |P6268$|P2111,|P2111 |P2111$|P1418,|P1418 |P1418$|P5385,|P5385 |P5385$|P3835,|P3835 |P3835$|P6266,|P6266 |P6266$|P5387,|P5387 |P5387$|P4859,|P4859 |P4859$|P7681,|P7681 |P7681$|P3834,|P3834 |P3834$|P4933,|P4933 |P4933$|P6212,|P6212 |P6212$|P4860,|P4860 |P4860$|P6833,|P6833 |P6833$|P8460,|P8460 |P8460$|P6211,|P6211 |P6211$|P10747,|P10747 |P10747$|P10454,|P10454 |P10454$|P8464,|P8464 |P8464$|P8463,|P8463 |P8463$|P9266,|P9266 |P9266$|P11590,|P11590 |P11590$|P4861,|P4861 |P4861$|P8894,|P8894 |P8894$|P8898,|P8898 |P8898$|P1013,|P1013 |P1013$|P11597,|P11597 |P11597$|P11589,|P11589 |P11589$|P4866,|P4866 |P4866$|P3244,|P3244 |P3244$|P10745,|P10745 |P10745$|P2891,|P2891 |P2891$|P4869,|P4869 |P4869$|P9257,|P9257 |P9257$|P6212,|P6212 |P6212$|P12587,|P12587 |P12587$|P3237,|P3237 |P3237$|P3241,|P3241 |P3241$|P13637,|P13637 |P13637$|P11579,|P11579 |P11579$|P12589,|P12589 |P12589$|P12591,|P12591 |P12591$|P11583,|P11583 |P11583$|P14707,|P14707 |P14707$|P13700,|P13700 |P13700$|P8894,|P8894 |P8894$|P2106,|P2106 |P2106$|P12589,|P12589 |P12589$|P12576,|P12576 |P12576$|P7678,|P7678 |P7678$|P8461,|P8461 |P8461$|P13641,|P13641 |P13641$|P13641,|P13641 |P13641$|P20415,|P20415 |P20415$|P14724,|P14724 |P14724$|P16136,|P16136 |P16136$|P20410,|P20410 |P20410$|P4866,|P4866 |P4866$|P14708,|P14708 |P14708$|P18793,|P18793 |P18793$|P21703,|P21703 |P21703$|P19074,|P19074 |P19074$|P14721,|P14721 |P14721$|P3833,|P3833 |P3833$|P18789,|P18789 |P18789$|P21710,|P21710 |P21710$|P14723,|P14723 |P14723$|P23425,|P23425 |P23425$|P21463,|P21463 |P21463$|P20413,|P20413 |P20413$|P20416,|P20416 |P20416$|P21463,|P21463 |P21463$|P28005,|P28005 |P28005$|P23153,|P23153 |P23153$|P14708,|P14708 |P14708$|P14722,|P14722 |P14722$|P17364,|P17364 |P17364$|P28464,|P28464 |P28464$|P13658,|P13658 |P13658$|P26467,|P26467 |P26467$|P23429,|P23429 |P23429$|P24602,|P24602 |P24602$|P24603,|P24603 |P24603$|P24602,|P24602 |P24602$|P24605,|P24605 |P24605$|P24848,|P24848 |P24848$|P24846,|P24846 |P24846$|P23429,|P23429 |P23429$|P24602,|P24602 |P24602$|P24603,|P24603 |P24603$|P29443,|P29443 |P29443$|P12961,|P12961 |P12961$|P12575,|P12575 |P12575$|P12564,|P12564 |P12564$|P29897,|P29897 |P29897$|P29898,|P29898 |P29898$|P29899,|P29899 |P29899$|P12584,|P12584 |P12584$|P2098,|P2098 |P2098$|P28008,|P28008 |P28008$|P29405,|P29405 |P29405$|P30609,|P30609 |P30609$|P28995,|P28995 |P28995$|P29443,|P29443 |P29443$|P29422,|P29422 |P29422$|P21570,|P21570 |P21570$|P29515,|P29515 |P29515$|P28929,|P28929 |P28929$|P13662,|P13662 |P13662$|P30076,|P30076 |P30076$|P31176,|P31176 |P31176$|P30610,|P30610 |P30610$|P20411,|P20411 |P20411$|P14704,|P14704 |P14704$|P29425,|P29425 |P29425$|P30071,|P30071 |P30071$|P31854,|P31854 |P31854$|P32852,|P32852 |P32852$|P31301,|P31301 |P31301$|P31298,|P31298 |P31298$|P31857,|P31857 |P31857$|P31856,|P31856 |P31856$|P32851,|P32851 |P32851$|P24604,|P24604 |P24604$|P24602,|P24602 |P24602$|P29421,|P29421 |P29421$|P24604,|P24604 |P24604$|P24848,|P24848 |P24848$|P29416,|P29416 |P29416$|P29417,|P29417 |P29417$|P29408,|P29408 |P29408$|P29421,|P29421 |P29421$|P29906,|P29906 |P29906$|P32857,|P32857 |P32857$|P31913,|P31913 |P31913$|P23146,|P23146 |P23146$|P23151,|P23151 |P23151$|P31909,|P31909 |P31909$|P31910,|P31910 |P31910$|P29422,|P29422 |P29422$|P30068,|P30068 |P30068$|P35873,|P35873 |P35873$|P27635,|P27635 |P27635$|P27636,|P27636 |P27636$|P27627,|P27627 |P27627$|P14,|P14 |P14$|P1,|P1 |P1$|P2,|P2 |P2$|P4,|P4 |P4$|P43454,|P43454 |P43454$"

dff = df_k1[df_k1['contractedfromwhichpatientsuspected'].astype(str).str.contains(ptr) | df_k1['patientnumber'].isin(ids)]
# df_k1['contractedfromwhichpatientsuspected'].unique()

In [ ]:
# for i in ids :
#     df_k1 = df_k1[df_k1['contractedfromwhichpatientsuspected'].astype(str).str.contains('P29,|P29 |P29$')]

In [167]:
dff.to_json("raw_data_all.json", orient='records')

In [164]:
df_k1[df_k1['contractedfromwhichpatientsuspected'].astype(str).str.contains('P29,|P29 |P29$')]

,agebracket,backupnotes,contractedfromwhichpatientsuspected,currentstatus,dateannounced,detectedcity,detecteddistrict,entryid,estimatedonsetdate,gender,nationality,notes,patientnumber,typeoftransmission
39,25,No travel history,P29,Hospitalized,09/03/2020,Tri Nagar,North Delhi,NaN,,F,India,No travel history,P40,Local

In [74]:
dfi.head()

,agebracket,backupnotes,contractedfromwhichpatientsuspected,currentstatus,dateannounced,detectedcity,detecteddistrict,detectedstate,estimatedonsetdate,gender,...,notes,numcases,patientnumber,source1,source2,source3,statecode,statepatientnumber,statuschangedate,typeoftransmission
0,20,Student from Wuhan,,Recovered,30/01/2020,Thrissur,Thrissur,Kerala,,F,...,Travelled from Wuhan,1,1,https://twitter.com/vijayanpinarayi/status/122...,https://weather.com/en-IN/india/news/news/2020...,,KL,KL-TS-P1,14/02/2020,Imported
1,,Student from Wuhan,,Recovered,02/02/2020,Alappuzha,Alappuzha,Kerala,,,...,Travelled from Wuhan,1,2,https://www.indiatoday.in/india/story/kerala-r...,https://weather.com/en-IN/india/news/news/2020...,,KL,KL-AL-P1,14/02/2020,Imported
2,,Student from Wuhan,,Recovered,03/02/2020,Kasaragod,Kasaragod,Kerala,,,...,Travelled from Wuhan,1,3,https://www.indiatoday.in/india/story/kerala-n...,https://twitter.com/ANI/status/122422148580539...,https://weather.com/en-IN/india/news/news/2020...,KL,KL-KS-P1,14/02/2020,Imported
3,45,Travel history to Italy and Austria,,Recovered,02/03/2020,East Delhi (Mayur Vihar),East Delhi,Delhi,,M,...,"Travelled from Austria, Italy",1,4,https://www.indiatoday.in/india/story/not-a-ja...,https://economictimes.indiatimes.com/news/poli...,,DL,DL-P1,15/03/2020,Imported
4,24,"Travel history to Dubai, Singapore contact",,Recovered,02/03/2020,Hyderabad,Hyderabad,Telangana,,M,...,"Travelled from Dubai to Bangalore on 20th Feb,...",1,5,https://www.deccanherald.com/national/south/qu...,https://www.indiatoday.in/india/story/coronavi...,https://www.thehindu.com/news/national/coronav...,TG,TS-P1,02/03/2020,Imported

In [168]:
dfi["currentstatus"].unique()

array(['Recovered', 'Hospitalized', 'Deceased', 'Migrated',
       'Migrated_Other', '', 'Migrated_other'], dtype=object)